### ISSUE TITLE
PDF/A-2B 6.2.11.4: CIDs vs. GIDs

### ISSUE THREAD

**Issue by a20god** [veraPDF/veraPDF-validation-profiles#147]
I guess veraPDF compares CIDSet against the GIDs for which there are glyphs in the embedded font, not taking CIDToGIDMap into account. 6.2.11.4 clearly talks about CIDs, not GIDs.

(Unfortunately, github doesn't let me attach a PDF document demonstrating the suspected issue.)

**Comment by a20god** [comment]
Forgot to mention that I'm talking about test 4 for 6.2.11.4.

**Comment by bdoubrov** [comment]
Hi, we'll double check the implementation. It would really help if you were able to provide a test file. Maybe via any file storage, if it is too large?

**Comment by a20god** [comment]
[CIDSet.PDF](https://github.com/veraPDF/veraPDF-validation-profiles/files/783383/CIDSet.PDF)

**Comment by bdoubrov** [comment]
Thanks for the test file. 

I see that the CIDSet entry indicates that there are only three glyphs present in the embedded font subset. The font file indeed contains only three non-empty glyphs, but it also contains a bunch of empty glyphs. Even if they are empty, this doesn't mean they are not present in the font program. For example, space glyph would often be like this.

This is exactly what veraPDF complains about: the font subset has many more glyphs than it is identified in the CIDSet entry.

**Comment by a20god** [comment]
The specification of the "loca" table says:
"If a glyph has no outline, then loca[n] = loca [n+1]."
There seems to be no other way to indicate missing glyphs.

Suppose we want to subset a font that has 65535 glyphs and we need glyph 65535 only.
If what you write above is true, PDF/A would require all 65535 glyphs to be included as CIDSet cannot be used to distinguish missing glyphs from empty glyphs. That would render subsetting for such a case quite useless. (Unless glyphs are renumbered to start at GID 1, requiring lots of effort for rearranging the GSUB/GPOS/GDEF tables.)

**Comment by a20god** [comment]
In other words, if what you write is true and the highest GID of a TrueType font is n, then the first n+1 bits of CIDSet must be 1 as there is no way to have missing glyphs in a TrueType font.

**Comment by a20god** [comment]
Interestingly, veraPDF does not complain if the same thing happens with a CFF font, even if "missing" glyphs have a non-empty font programme (consisting of just the endchar operator).
[CIDSet-CFF.pdf](https://github.com/veraPDF/veraPDF-validation-profiles/files/783509/CIDSet-CFF.pdf)

**Comment by bdoubrov** [comment]
This second test file is PDF/A-1 document. Here the requirements on CIDSet are a different. See the discussion in https://github.com/veraPDF/veraPDF-library/issues/708

**Comment by a20god** [comment]
Oops, sorry. So this issue affects both TrueType and CFF fonts. According to your interpretation, both types of fonts cannot have missing CIDs below the highest CID and therefore CIDSet could be just an integer specifying the highest CID present in the font. CIDSet being a bit set rather than an integer is (for me) a clue that the intention was to allow missing CIDs below the highest CID. Probably we need a clarification from the committee on the exact meaning of "CIDs which are present in the font program".

If CIDSet really is a bit set and the intention is allowing for missing CIDs in subsetted fonts: how shall those missing CIDs be encoded in the embedded font stream? For TrueType, the font programme can be left empty, CFF requires an endchar operator...

**Comment by a20god** [comment]
(Some of my comments assume that (for TrueType) CIDToGIDMap is /Identity or a stream specifying the identity or (for CFF) charset is the identity.)

Please have a look at this slightly modified document:
[CIDSet-2.pdf](https://github.com/veraPDF/veraPDF-validation-profiles/files/786157/CIDSet-2.pdf)

veraPDF still claims that test 4 for 6.2.11.4 fails. However, there are no bits in CIDSet that are zero and for which there are GIDs (according to CIDToGIDMap) with glyphs "present in the font program" (using any definition of "present in the font program").

In other words, for every glyph "present in the font program" (that is, GIDs 0 through 87 when including glyphs with empty outlines) there is either
- a CID which maps to that GID and the bit corresponding to that CID is set in CIDSet or
- CIDToGIDMap does not map any CID to that GID.

3-Height's PDF/A validator reports that  both CIDSet.PDF and CIDSet-2.pdf are conforming,
callas pdfaPilot 6.3.260 reports that CIDSet-2.pdf is conforming, but CIDSet.PDF isn't,
veraPDF reports that both CIDSet.PDF and CIDSet-2.pdf are non-conforming. That situation is not a good one.

veraPDF is probably right to treat glyph 0 as being present (despite its outline being empty) due to
"Every CIDFont shall contain a glyph description for CID 0" of ISO 32000-1:2008, 9.7.4.2. However,
we may need clarification for other GIDs (and for the issues described below) from the committees.

There's a problem in the definition of "CIDSet" of ISO 32000-1:2008 (and PDF Reference 1.4). It defines CIDSet as:
"A stream identifying which CIDs are present in the CIDFont file." However, it does not define "CIDfont file". The definition of "CIDFont file" in Adobe Technical Note #5014 begins like this:
"CIDFont files are PostScript language programs that adopt a restrictive syntax [...]" This does not include TrueType fonts! (It even does include OpenType fonts with CFF outlines.)

That is, the meaning of CIDSet is not properly defined for TrueType fonts anyway and PDF/A-1 should never have required CIDSet to be present for both types (TrueType and CFF) of CIDFonts.

The best solution for me (as Creator of PDF Documents) is to omit CIDSet for PDF/A-2 and PDF/A-3 documents as the standards are broken wr.t. CIDSet. CIDSet will be deprecated in PDF 2.0 anyway.

**Comment by bdoubrov** [comment]
Thanks for yet another test file. We'll double check the implementation and fix it, if the issue confirmed.

I do agree the CIDSet for CIDFontType2 (based on TrueType) looks very confusing. As you correctly point out, there is no way in TrueType format to distinguish between non-existent glyphs and glyphs with empty outlines (as SPACE). As a reuslt, we have to assume that all glyphs with GIDs from 0 to number of Glyphs-1 are present in the embedded font file.

I note however, this the situation is different for CIDSetType0, where CFF format does not require CIDs in the embdded subset to form a single range.

And I fully agree with you, as CIDSet/CharSet seem to be irrelevant for PDF rendering and as there entries are not mandatory in PDF/A-2 and 3 standards, the easiest approach for creators would be simply to omit these entries.

**Comment by bdoubrov** [comment]
We've fixed the logic of verifying CIDSet. Now it is consistent with the above discussion. In particular, your file CIDSet-2.pdf is now validated as conforming PDF/A-2 document.

However, CIDSet.pdf is still considered asinvalidfor the reasons dicsussed above: empty glyphs in the TrueType subset are still considered as if they are present in the file program, but have no outlines.

The fix is available in the dev version 1.1.29: 
http://downloads.verapdf.org/dev/verapdf-1.1.29-GF-installer.zip

**Comment by DarrenHoffman** [comment]
thanks for that discussion. I hadn't previously considered the case of mapping unsused CIDs to a GID > than the max GID in the font file. As is pointed out, though, you can't do that if you need GID 65535. 

However, wouldn't it be ok to use a "custom" CID character collection with CIDs in the range of 1 to N, where N is the number of characters you need in your subset? That is, if you only need GID 65535, then just use CID 1, and map CID 1 to GID 65535 in the CIDtoGIDMap. The CIDset then only needs to include CID 1 because all other CIDs have no defined mapping to any GID. Of course you need a custom ToUnicode map as well, but it would be small.

As I understand it, CIDSets were meant to be useful when merging documents that contained different subsets of the same font. I wonder if anybody has ever actually cared, especially I wonder about it for TrueType CID fonts. oh well.
