### ISSUE TITLE
Some profiles have inconsistent profile and main Reference clauses

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-validation-profiles#60]
Each Rule is identified by a clause and test number, ideally there will be a 1 to 1 correspondence between the IDs and clauses. Automated parsing and checking have revealed that in the main PDF/A1-B profile this is not the case. Some differ, others are truncations, e.g. ```6.2.3.2``` to ```6.2.3```, and some have multiple Clause ids. The auto detected list of ids and reference clauses is below:
```
  Test ID       Clause
  -------       -------
  6-1-11-t02    6.1.7
  6-2-4-t02     6.2.5
  6-2-3-t02     6.2.3.3
  6-3-3-t03     6.3.3.3
  6-2-3-t04     6.2.3.3
  6-1-11-t01    6.1.7
  6-3-3-t02     6.3.3.2
  6-2-3-t03     6.2.3.3
  6-2-3-t05     6.2.2, 6.2.3.2
  6-6-2-t02     6.6.2, 6.9
  6-3-3-t01     6.3.3.1
```
Could somebody please check the individual rule files for the above and verify?

**Comment by carlwilson** [comment]
@bdoubrov you may want to look?

**Comment by bdoubrov** [comment]
6-1-11-t01, 6-1-11-t02: fixed

6-2-4-t04: correct, contains references to both 6.2.4 and 6.2.5

6-2-3-t02, 6-2-3-t03, 6-2-3-t04, 6-3-3-t01, 6-3-3-t02, 6-3-3-t03: correct. The specification is more fine-grained than our rules structure. I’m not sure if we want to change this

6-2-3-t05: fixed

6-6-2-t02: the references are OK, but I think we have to be consistent when we refer to several clauses. See 6-2-4-t04, where there are two individual reference tags, one per each clause

**Comment by DmitryRemezow** [comment]
@bdoubrov i have a question about 6-2-4-t02 profile.

This rules shall be applied only to Form and Image XObject. But 6-2-4 profile used "PDXObject" as a rule object. This means that this rule applies to the PostScript XObject. I create test file with PostScript XObject, which contains OPI key.  This key is ignored by all validator tools, except our validator. It's expected behavior?

**Comment by bdoubrov** [comment]
Agreed, we'd better be more careful here and instead of a single validation rupe for XObject have two separate ones for forms and images. This will also resolve the issue with two clause references

**Comment by carlwilson** [comment]
I'm assuming that this is now sorted.
